version: "3.9"
services:

  # frontend-app:
  #   build: frontend/.
  #   ports:
  #     - "8080:80"
  #   networks:
  #     - services_network
  
  location-api:
    build: 
      context: backend/.
      dockerfile: Dockerfile.location
    expose:
      - 5001
    ports:
      - "5001:5001"
    networks:
      - services_network

  weather-api:
    build:
      context: backend/.
      dockerfile: Dockerfile.weather
    expose:
      - 5002
    ports:
      - "5002:5002"
    networks:
      - services_network

networks:
  services_network:
    driver: bridge